jgcaballero_lab3: jgcaballero_prime.o jgcaballero_lab3.c
	gcc jgcaballero_lab3.c jgcaballero_prime.o -o jgcaballero_lab3

jgcaballero_prime.o: jgcaballero_prime.c jgcaballero_prime.h
	gcc -c jgcaballero_prime.c

clean:
	rm *.o; rm jgcaballero_lab3
